### ISSUE TITLE
我们应该如何分工呢？

### ISSUE THREAD

**Issue by wangchenhong** [wutcst/sept2-fullrub#5]

**Comment by f-xiu** [comment]
### 公共任务
1. 掌握github，代码规范，单元测试，分支与基线、CI/CD等软件开发方法

2. 共同参与项目管理与任务分配、分支模型与代码合并、代码规范与评审、工程打包与持续集成

**Comment by f-xiu** [comment]
### 开发任务
### 方嘉豪

1. 前端项目结构
2. 界面玩法设计
3. 游戏地图关卡设计
4. 游戏开发
5. 单元测试
6. 前后端对接
7. 相关文档编写

### 王晨宏 

1. 后端项目结构
2. 后端功能设计
3. 后端功能模块编写
4. 单元测试
5. 相关文档编写

### 陈宇沥

1. 游戏数据设计
2. 找游戏素材
3. 数据库设计开发
4. 数据库dao层编写
5. 相关文档编写

**Comment by f-xiu** [comment]
### 测试任务
所有人负责自己编写的代码的单元测试
### 方嘉豪
端到端测试

### 王晨宏
集成测试

### 陈宇沥
性能等其他方面的测试

**Comment by f-xiu** [comment]
### CI/CD
持续集成（CI）
在自动化构建、自动化测试和自动化部署等过程，以确保代码的质量和可靠性，并尽早发现和解决问题。

持续交付/部署（CD）
旨在自动化构建、测试和部署应用程序，并将其交付到生产环境中。

负责自动化构建、测试、部署过程：
  前端：方嘉豪
  后端：陈宇沥 、王晨宏
最终部署：方嘉豪、陈宇沥 、王晨宏
